languageName = "Portugês (Brasileiro)"
title = "Jefferson Oliveira"
copyright = "© Jefferson Oliveira - Todo conteúdo distribuido por este website são refletem minhas próprias opiniões e estão sob a licença <br/><a href=\"https://creativecommons.org/licenses/by/4.0/\">Creative Commons Attribution 4.0 International License.</a>"

[params]
subtitle = "Olá! Eu sou Jefferson Oliveira, um engenheiro de software curioso e apaixonado por tecnologia."
owner = "Jefferson Oliveira"
keywords = "Jefferson Oliveira, engenheiro de software, desenvolvedor, brasil"
copyright = "Jefferson Oliveira | CC BY 4.0"
menuMore = "Ver mais"
readMore = "Ler mais"
readOtherPosts = "Ler outros artigos"
newerPosts = "Artigos recentes"
olderPosts = "Artigos antigos"
missingContentMessage = "Página não encontrada..."
missingBackButtonLabel = "Voltar para a página inicial"
minuteReadingTime = "min de leitura"
words = "palavras"
newTab = true

[params.logo]
logoText = "Jefferson Oliveira"
logoHomeLink = "/pt-BR"

[menu]
[[menu.main]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/jeffersonmourak/"
weight = 1
newTab = true
[[menu.main]]
identifier = "github"
name = "Github"
url = "https://github.com/jeffersonmourak"
weight = 2
[[menu.main]]
identifier = "email"
name = "Email"
url = "mailto:jeffersonmourak@gmail.com"
weight = 3
[[menu.main]]
identifier = "instagram"
name = "Instagram"
url = "https://instagram.com/jeffersonmourak"
weight = 4
[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/pt-br/posts"
weight = 5
[[menu.main]]
identifier = "voting_poker"
name = "Voting Poker"
url = "https://voting.poker"
weight = 6
